#include <iostream> // --trace
#include <iterator> // __gnu_cxx::__normal_iterator
#include <memory> // std::allocator
#include <sstream> // __str__
#include <vector> // std::vector

#include <pybind11/pybind11.h>
#include <functional>
#include <string>
#include <mmtf.hpp>


#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*);
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>);
#endif

void bind_std_stl_vector_5(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	std::cout << "B176_[std::vector<mmtf::GroupType>] ";
	{ // std::vector file:bits/stl_vector.h line:216
		pybind11::class_<std::vector<mmtf::GroupType>, std::shared_ptr<std::vector<mmtf::GroupType>>> cl(M("std"), "vector_mmtf_GroupType_t", "");
		pybind11::handle cl_type = cl;

		cl.def( pybind11::init( [](){ return new std::vector<mmtf::GroupType>(); } ) );
		cl.def( pybind11::init<const class std::allocator<struct mmtf::GroupType> &>(), pybind11::arg("__a") );

		cl.def( pybind11::init( [](unsigned long const & a0){ return new std::vector<mmtf::GroupType>(a0); } ), "doc");
		cl.def( pybind11::init<unsigned long, const class std::allocator<struct mmtf::GroupType> &>(), pybind11::arg("__n"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](unsigned long const & a0, const struct mmtf::GroupType & a1){ return new std::vector<mmtf::GroupType>(a0, a1); } ), "doc");
		cl.def( pybind11::init<unsigned long, const struct mmtf::GroupType &, const class std::allocator<struct mmtf::GroupType> &>(), pybind11::arg("__n"), pybind11::arg("__value"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](std::vector<mmtf::GroupType> const &o){ return new std::vector<mmtf::GroupType>(o); } ) );
		cl.def( pybind11::init<const class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > &, const class std::allocator<struct mmtf::GroupType> &>(), pybind11::arg("__x"), pybind11::arg("__a") );

		cl.def("assign", (class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > & (std::vector<mmtf::GroupType>::*)(const class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > &)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::operator=, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::operator=(const class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > &) --> class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > &", pybind11::return_value_policy::automatic, pybind11::arg("__x"));
		cl.def("assign", (void (std::vector<mmtf::GroupType>::*)(unsigned long, const struct mmtf::GroupType &)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::assign, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::assign(unsigned long, const struct mmtf::GroupType &) --> void", pybind11::arg("__n"), pybind11::arg("__val"));
		cl.def("begin", (class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::begin, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::begin() --> class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >");
		cl.def("end", (class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::end, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::end() --> class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >");
		cl.def("cbegin", (class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)() const) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::cbegin, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::cbegin() const --> class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >");
		cl.def("cend", (class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)() const) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::cend, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::cend() const --> class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >");
		cl.def("size", (unsigned long (std::vector<mmtf::GroupType>::*)() const) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::size, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::size() const --> unsigned long");
		cl.def("max_size", (unsigned long (std::vector<mmtf::GroupType>::*)() const) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::max_size, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::max_size() const --> unsigned long");
		cl.def("resize", (void (std::vector<mmtf::GroupType>::*)(unsigned long)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::resize, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::resize(unsigned long) --> void", pybind11::arg("__new_size"));
		cl.def("resize", (void (std::vector<mmtf::GroupType>::*)(unsigned long, const struct mmtf::GroupType &)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::resize, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::resize(unsigned long, const struct mmtf::GroupType &) --> void", pybind11::arg("__new_size"), pybind11::arg("__x"));
		cl.def("shrink_to_fit", (void (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::shrink_to_fit, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::shrink_to_fit() --> void");
		cl.def("capacity", (unsigned long (std::vector<mmtf::GroupType>::*)() const) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::capacity, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::capacity() const --> unsigned long");
		cl.def("empty", (bool (std::vector<mmtf::GroupType>::*)() const) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::empty, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::empty() const --> bool");
		cl.def("reserve", (void (std::vector<mmtf::GroupType>::*)(unsigned long)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::reserve, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::reserve(unsigned long) --> void", pybind11::arg("__n"));
		cl.def("__getitem__", (struct mmtf::GroupType & (std::vector<mmtf::GroupType>::*)(unsigned long)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::operator[], "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::operator[](unsigned long) --> struct mmtf::GroupType &", pybind11::return_value_policy::automatic, pybind11::arg("__n"));
		cl.def("at", (struct mmtf::GroupType & (std::vector<mmtf::GroupType>::*)(unsigned long)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::at, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::at(unsigned long) --> struct mmtf::GroupType &", pybind11::return_value_policy::automatic, pybind11::arg("__n"));
		cl.def("front", (struct mmtf::GroupType & (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::front, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::front() --> struct mmtf::GroupType &", pybind11::return_value_policy::automatic);
		cl.def("back", (struct mmtf::GroupType & (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::back, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::back() --> struct mmtf::GroupType &", pybind11::return_value_policy::automatic);
		cl.def("data", (struct mmtf::GroupType * (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::data, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::data() --> struct mmtf::GroupType *", pybind11::return_value_policy::automatic);
		cl.def("push_back", (void (std::vector<mmtf::GroupType>::*)(const struct mmtf::GroupType &)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::push_back, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::push_back(const struct mmtf::GroupType &) --> void", pybind11::arg("__x"));
		cl.def("pop_back", (void (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::pop_back, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::pop_back() --> void");
		cl.def("insert", (class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >, const struct mmtf::GroupType &)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::insert, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::insert(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >, const struct mmtf::GroupType &) --> class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >", pybind11::arg("__position"), pybind11::arg("__x"));
		cl.def("insert", (class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >, unsigned long, const struct mmtf::GroupType &)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::insert, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::insert(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >, unsigned long, const struct mmtf::GroupType &) --> class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >", pybind11::arg("__position"), pybind11::arg("__n"), pybind11::arg("__x"));
		cl.def("erase", (class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::erase, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::erase(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >) --> class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >", pybind11::arg("__position"));
		cl.def("erase", (class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > > (std::vector<mmtf::GroupType>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >, class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::erase, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::erase(class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >, class __gnu_cxx::__normal_iterator<const struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >) --> class __gnu_cxx::__normal_iterator<struct mmtf::GroupType *, class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > >", pybind11::arg("__first"), pybind11::arg("__last"));
		cl.def("swap", (void (std::vector<mmtf::GroupType>::*)(class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > &)) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::swap, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::swap(class std::vector<struct mmtf::GroupType, class std::allocator<struct mmtf::GroupType> > &) --> void", pybind11::arg("__x"));
		cl.def("clear", (void (std::vector<mmtf::GroupType>::*)()) &std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::clear, "C++: std::vector<mmtf::GroupType, std::allocator<mmtf::GroupType> >::clear() --> void");
	}
	std::cout << "B177_[std::vector<short>] ";
	{ // std::vector file:bits/stl_vector.h line:216
		pybind11::class_<std::vector<short>, std::shared_ptr<std::vector<short>>> cl(M("std"), "vector_short_t", "");
		pybind11::handle cl_type = cl;

		cl.def( pybind11::init( [](){ return new std::vector<short>(); } ) );
		cl.def( pybind11::init<const class std::allocator<short> &>(), pybind11::arg("__a") );

		cl.def( pybind11::init( [](unsigned long const & a0){ return new std::vector<short>(a0); } ), "doc");
		cl.def( pybind11::init<unsigned long, const class std::allocator<short> &>(), pybind11::arg("__n"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](unsigned long const & a0, const short & a1){ return new std::vector<short>(a0, a1); } ), "doc");
		cl.def( pybind11::init<unsigned long, const short &, const class std::allocator<short> &>(), pybind11::arg("__n"), pybind11::arg("__value"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](std::vector<short> const &o){ return new std::vector<short>(o); } ) );
		cl.def( pybind11::init<const class std::vector<short, class std::allocator<short> > &, const class std::allocator<short> &>(), pybind11::arg("__x"), pybind11::arg("__a") );

		cl.def("assign", (class std::vector<short, class std::allocator<short> > & (std::vector<short>::*)(const class std::vector<short, class std::allocator<short> > &)) &std::vector<short, std::allocator<short> >::operator=, "C++: std::vector<short, std::allocator<short> >::operator=(const class std::vector<short, class std::allocator<short> > &) --> class std::vector<short, class std::allocator<short> > &", pybind11::return_value_policy::automatic, pybind11::arg("__x"));
		cl.def("assign", (void (std::vector<short>::*)(unsigned long, const short &)) &std::vector<short, std::allocator<short> >::assign, "C++: std::vector<short, std::allocator<short> >::assign(unsigned long, const short &) --> void", pybind11::arg("__n"), pybind11::arg("__val"));
		cl.def("begin", (class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::begin, "C++: std::vector<short, std::allocator<short> >::begin() --> class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > >");
		cl.def("end", (class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::end, "C++: std::vector<short, std::allocator<short> >::end() --> class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > >");
		cl.def("cbegin", (class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)() const) &std::vector<short, std::allocator<short> >::cbegin, "C++: std::vector<short, std::allocator<short> >::cbegin() const --> class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >");
		cl.def("cend", (class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)() const) &std::vector<short, std::allocator<short> >::cend, "C++: std::vector<short, std::allocator<short> >::cend() const --> class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >");
		cl.def("size", (unsigned long (std::vector<short>::*)() const) &std::vector<short, std::allocator<short> >::size, "C++: std::vector<short, std::allocator<short> >::size() const --> unsigned long");
		cl.def("max_size", (unsigned long (std::vector<short>::*)() const) &std::vector<short, std::allocator<short> >::max_size, "C++: std::vector<short, std::allocator<short> >::max_size() const --> unsigned long");
		cl.def("resize", (void (std::vector<short>::*)(unsigned long)) &std::vector<short, std::allocator<short> >::resize, "C++: std::vector<short, std::allocator<short> >::resize(unsigned long) --> void", pybind11::arg("__new_size"));
		cl.def("resize", (void (std::vector<short>::*)(unsigned long, const short &)) &std::vector<short, std::allocator<short> >::resize, "C++: std::vector<short, std::allocator<short> >::resize(unsigned long, const short &) --> void", pybind11::arg("__new_size"), pybind11::arg("__x"));
		cl.def("shrink_to_fit", (void (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::shrink_to_fit, "C++: std::vector<short, std::allocator<short> >::shrink_to_fit() --> void");
		cl.def("capacity", (unsigned long (std::vector<short>::*)() const) &std::vector<short, std::allocator<short> >::capacity, "C++: std::vector<short, std::allocator<short> >::capacity() const --> unsigned long");
		cl.def("empty", (bool (std::vector<short>::*)() const) &std::vector<short, std::allocator<short> >::empty, "C++: std::vector<short, std::allocator<short> >::empty() const --> bool");
		cl.def("reserve", (void (std::vector<short>::*)(unsigned long)) &std::vector<short, std::allocator<short> >::reserve, "C++: std::vector<short, std::allocator<short> >::reserve(unsigned long) --> void", pybind11::arg("__n"));
		cl.def("__getitem__", (short & (std::vector<short>::*)(unsigned long)) &std::vector<short, std::allocator<short> >::operator[], "C++: std::vector<short, std::allocator<short> >::operator[](unsigned long) --> short &", pybind11::return_value_policy::automatic, pybind11::arg("__n"));
		cl.def("at", (short & (std::vector<short>::*)(unsigned long)) &std::vector<short, std::allocator<short> >::at, "C++: std::vector<short, std::allocator<short> >::at(unsigned long) --> short &", pybind11::return_value_policy::automatic, pybind11::arg("__n"));
		cl.def("front", (short & (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::front, "C++: std::vector<short, std::allocator<short> >::front() --> short &", pybind11::return_value_policy::automatic);
		cl.def("back", (short & (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::back, "C++: std::vector<short, std::allocator<short> >::back() --> short &", pybind11::return_value_policy::automatic);
		cl.def("data", (short * (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::data, "C++: std::vector<short, std::allocator<short> >::data() --> short *", pybind11::return_value_policy::automatic);
		cl.def("push_back", (void (std::vector<short>::*)(const short &)) &std::vector<short, std::allocator<short> >::push_back, "C++: std::vector<short, std::allocator<short> >::push_back(const short &) --> void", pybind11::arg("__x"));
		cl.def("pop_back", (void (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::pop_back, "C++: std::vector<short, std::allocator<short> >::pop_back() --> void");
		cl.def("insert", (class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >, const short &)) &std::vector<short, std::allocator<short> >::insert, "C++: std::vector<short, std::allocator<short> >::insert(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >, const short &) --> class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > >", pybind11::arg("__position"), pybind11::arg("__x"));
		cl.def("insert", (class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >, unsigned long, const short &)) &std::vector<short, std::allocator<short> >::insert, "C++: std::vector<short, std::allocator<short> >::insert(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >, unsigned long, const short &) --> class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > >", pybind11::arg("__position"), pybind11::arg("__n"), pybind11::arg("__x"));
		cl.def("erase", (class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >)) &std::vector<short, std::allocator<short> >::erase, "C++: std::vector<short, std::allocator<short> >::erase(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >) --> class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > >", pybind11::arg("__position"));
		cl.def("erase", (class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > > (std::vector<short>::*)(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >, class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >)) &std::vector<short, std::allocator<short> >::erase, "C++: std::vector<short, std::allocator<short> >::erase(class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >, class __gnu_cxx::__normal_iterator<const short *, class std::vector<short, class std::allocator<short> > >) --> class __gnu_cxx::__normal_iterator<short *, class std::vector<short, class std::allocator<short> > >", pybind11::arg("__first"), pybind11::arg("__last"));
		cl.def("swap", (void (std::vector<short>::*)(class std::vector<short, class std::allocator<short> > &)) &std::vector<short, std::allocator<short> >::swap, "C++: std::vector<short, std::allocator<short> >::swap(class std::vector<short, class std::allocator<short> > &) --> void", pybind11::arg("__x"));
		cl.def("clear", (void (std::vector<short>::*)()) &std::vector<short, std::allocator<short> >::clear, "C++: std::vector<short, std::allocator<short> >::clear() --> void");
	}
}
