name: 'Compile binder'
description: 'Binder'
inputs:
  theextraargument:   # an optional extra argument for docker run.
    description: 'Extra docker argument'
    required: true
    default: 'World'
outputs:
  thestatus: # here we put the execution status 
    description: 'The execution status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.theextraargument }}
