on:
  schedule:
    - cron: '* 1 * * *'
jobs:
  compilejobcentos7night:
    runs-on: ubuntu-latest
    name: Checkout_and_compile_binder_on_centos7
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: hello
      uses: ./.github/workflows/centos7night
    # Use the output from the `hello` step
    - name: Get the output status
      run: echo "The status was ${{ steps.hello.outputs.out }}"
